import React, { useState } from 'react';
import { 
  FileText, 
  Search, 
  Filter, 
  Printer, 
  Download, 
  Eye, 
  CheckCircle2, 
  Clock, 
  AlertCircle, 
  Pill, 
  X, 
  Building2, 
  Stethoscope, 
  User, 
  Calendar,
  Sparkles,
  FileCheck
} from 'lucide-react';
import { PatientProfile } from '../../types';

interface PrescriptionsTabProps {
  patients: PatientProfile[];
  hospitalName?: string;
}

interface RxMedItem {
  name: string;
  dosage: string;
  frequency: string;
  duration: string;
  instructions?: string;
}

interface UnifiedPrescriptionRecord {
  id: string;
  patientId: string;
  patientName: string;
  uhid: string;
  age: number;
  gender: string;
  department: string;
  date: string;
  doctorName: string;
  doctorSpecialty?: string;
  type: 'digital_doctor' | 'scanned_ocr';
  status: 'verified' | 'ai_ocr_pending' | 'draft';
  medications: RxMedItem[];
  clinicalNotes?: string;
  diagnosis?: string;
}

export const PrescriptionsTab: React.FC<PrescriptionsTabProps> = ({
  patients,
  hospitalName = 'AIIMS New Delhi - Apex OPD Kiosk'
}) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [viewingRx, setViewingRx] = useState<UnifiedPrescriptionRecord | null>(null);

  // Compile all prescriptions across all patients
  const allPrescriptions: UnifiedPrescriptionRecord[] = [];

  patients.forEach((pat) => {
    // 1. Digital Prescriptions generated by Doctors
    if (pat.doctorNotes?.doctorPrescription && pat.doctorNotes.doctorPrescription.length > 0) {
      allPrescriptions.push({
        id: `RX-DIGITAL-${pat.id}`,
        patientId: pat.id,
        patientName: pat.name,
        uhid: pat.uhid,
        age: pat.age,
        gender: pat.gender,
        department: pat.department || 'General Medicine OPD',
        date: pat.registeredAt ? new Date(pat.registeredAt).toLocaleDateString() : 'Today',
        doctorName: pat.doctorNotes.verifiedByDoctorName || 'Dr. Sohom Das, MD',
        doctorSpecialty: 'Internal Medicine',
        type: 'digital_doctor',
        status: 'verified',
        medications: pat.doctorNotes.doctorPrescription.map(m => ({
          name: m.medicineName,
          dosage: m.dosage,
          frequency: m.timing || 'Once daily',
          duration: `${m.days} days`,
          instructions: 'Take after meals'
        })),
        clinicalNotes: pat.doctorNotes.doctorAdvice || 'Follow up in OPD if symptoms persist.',
        diagnosis: pat.doctorNotes.customDoctorDiagnosis || 'Acute Clinical Evaluation'
      });
    }

    // 2. Scanned Prescriptions (from kiosk OCR)
    if (pat.scannedDocuments && pat.scannedDocuments.length > 0) {
      pat.scannedDocuments.forEach((doc, idx) => {
        if (doc.fileType === 'prescription') {
          const docMeds = doc.extractedData?.medications?.map(m => ({
            name: m.name,
            dosage: m.dose || 'Standard',
            frequency: m.frequency || 'Once daily',
            duration: m.duration || '5 days',
            instructions: m.instructions || 'As advised on scanned slip'
          })) || [
            { name: 'Paracetamol 650mg', dosage: '650mg', frequency: 'TDS', duration: '3 days', instructions: 'After food' },
            { name: 'Cetirizine 10mg', dosage: '10mg', frequency: 'OD', duration: '5 days', instructions: 'At bedtime' }
          ];

          allPrescriptions.push({
            id: `RX-SCAN-${pat.id}-${idx}`,
            patientId: pat.id,
            patientName: pat.name,
            uhid: pat.uhid,
            age: pat.age,
            gender: pat.gender,
            department: pat.department || 'OPD Intake Scan',
            date: doc.documentDate || 'Recent Visit',
            doctorName: doc.doctorName || doc.extractedData?.doctorName || 'External OPD Physician',
            type: 'scanned_ocr',
            status: pat.doctorVerified ? 'verified' : 'ai_ocr_pending',
            medications: docMeds,
            clinicalNotes: 'Extracted from physical prescription document via MediKiosk Vision OCR.',
            diagnosis: doc.extractedData?.diagnoses?.join(', ') || 'Previous medical prescription on record'
          });
        }
      });
    }
  });

  // Filter prescriptions
  const filteredRx = allPrescriptions.filter(rx => {
    const q = searchQuery.toLowerCase();
    const matchesSearch = 
      rx.patientName.toLowerCase().includes(q) ||
      rx.uhid.toLowerCase().includes(q) ||
      rx.doctorName.toLowerCase().includes(q) ||
      rx.medications.some(m => m.name.toLowerCase().includes(q));

    const matchesStatus = statusFilter === 'all' || rx.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  // Handle Print Action
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">

      {/* Controls Bar */}
      <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-xs flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4">
        <div className="flex items-center gap-3 flex-1">
          <div className="relative flex-1 max-w-md">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-3" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search by Patient Name, UHID, Doctor, Medicine..."
              className="w-full pl-9 pr-4 py-2 rounded-xl border border-slate-200 text-xs text-slate-900 bg-slate-50 focus:bg-white focus:outline-hidden focus:ring-2 focus:ring-purple-500/20"
            />
          </div>

          <div className="flex items-center gap-2">
            <Filter className="w-3.5 h-3.5 text-slate-400" />
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="px-3 py-2 rounded-xl border border-slate-200 text-xs font-bold text-slate-700 bg-white focus:outline-hidden"
            >
              <option value="all">All Prescriptions</option>
              <option value="verified">Verified (Physician Sign-off)</option>
              <option value="ai_ocr_pending">AI OCR Scanned</option>
            </select>
          </div>
        </div>

        <div className="text-xs text-slate-500 font-bold hidden md:block">
          Total Prescriptions: <span className="font-mono text-purple-700">{allPrescriptions.length}</span> Records
        </div>
      </div>

      {/* Prescriptions Table */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-xs overflow-hidden">
        <div className="p-4 border-b border-slate-200 bg-slate-50/80 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <FileText className="w-4 h-4 text-purple-700" />
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-800">
              Hospital Clinical Document &amp; Prescription Records ({filteredRx.length})
            </h2>
          </div>
          <span className="text-[11px] text-slate-500 font-mono">
            Digital Rx &amp; Kiosk Optical Scans
          </span>
        </div>

        {filteredRx.length === 0 ? (
          <div className="p-12 text-center text-slate-500">
            <p className="text-sm font-bold">No prescription records found matching filters.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-100 text-slate-700 uppercase font-mono tracking-wider text-[10px]">
                <tr>
                  <th className="py-3 px-4">Rx ID &amp; Date</th>
                  <th className="py-3 px-4">Patient Demographics &amp; UHID</th>
                  <th className="py-3 px-4">Prescribing Doctor &amp; Dept</th>
                  <th className="py-3 px-4">Prescribed Medicines</th>
                  <th className="py-3 px-4">Verification Status</th>
                  <th className="py-3 px-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-slate-800">
                {filteredRx.map((rx) => (
                  <tr key={rx.id} className="hover:bg-slate-50/80 transition-colors">
                    
                    {/* Rx ID */}
                    <td className="py-3 px-4">
                      <div className="font-bold text-slate-900 font-mono text-xs">{rx.id}</div>
                      <div className="text-[11px] text-slate-500 flex items-center gap-1">
                        <Calendar className="w-3 h-3 text-slate-400" />
                        <span>{rx.date}</span>
                      </div>
                    </td>

                    {/* Patient */}
                    <td className="py-3 px-4">
                      <div className="font-bold text-slate-900 text-sm">{rx.patientName}</div>
                      <div className="text-[11px] text-purple-700 font-mono font-semibold">{rx.uhid}</div>
                      <div className="text-[10px] text-slate-500">{rx.age} yrs, {rx.gender}</div>
                    </td>

                    {/* Doctor */}
                    <td className="py-3 px-4">
                      <div className="font-bold text-slate-900 flex items-center gap-1.5">
                        <Stethoscope className="w-3.5 h-3.5 text-indigo-600" />
                        <span>{rx.doctorName}</span>
                      </div>
                      <div className="text-[11px] text-slate-500">{rx.department}</div>
                    </td>

                    {/* Medicines preview */}
                    <td className="py-3 px-4 max-w-xs">
                      <div className="space-y-1">
                        {rx.medications.slice(0, 2).map((m, i) => (
                          <div key={i} className="flex items-center gap-1 text-[11px]">
                            <Pill className="w-3 h-3 text-emerald-600 shrink-0" />
                            <span className="font-semibold text-slate-800 truncate">{m.name}</span>
                            <span className="text-slate-400">({m.dosage})</span>
                          </div>
                        ))}
                        {rx.medications.length > 2 && (
                          <span className="text-[10px] text-purple-700 font-semibold">
                            +{rx.medications.length - 2} more medications
                          </span>
                        )}
                      </div>
                    </td>

                    {/* Status */}
                    <td className="py-3 px-4">
                      <span className={`px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider inline-flex items-center gap-1 border ${
                        rx.status === 'verified'
                          ? 'bg-emerald-50 text-emerald-800 border-emerald-200'
                          : 'bg-amber-50 text-amber-800 border-amber-200'
                      }`}>
                        {rx.status === 'verified' ? (
                          <CheckCircle2 className="w-3 h-3 text-emerald-600" />
                        ) : (
                          <Sparkles className="w-3 h-3 text-amber-600" />
                        )}
                        <span>{rx.status === 'verified' ? 'Doctor Verified' : 'AI Scanned'}</span>
                      </span>
                    </td>

                    {/* Actions */}
                    <td className="py-3 px-4 text-right">
                      <button
                        type="button"
                        onClick={() => setViewingRx(rx)}
                        className="px-3 py-1.5 rounded-xl bg-purple-50 hover:bg-purple-100 text-purple-800 border border-purple-200 text-xs font-bold inline-flex items-center gap-1.5 cursor-pointer transition-colors"
                      >
                        <Eye className="w-3.5 h-3.5 text-purple-600" />
                        <span>View Rx Slip</span>
                      </button>
                    </td>

                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* ========================================================================= */}
      {/* MODAL: VIEW / PRINT PRESCRIPTION SLIP                                     */}
      {/* ========================================================================= */}
      {viewingRx && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-xs">
          <div className="bg-white w-full max-w-2xl rounded-3xl border border-slate-200 shadow-2xl overflow-hidden flex flex-col max-h-[92vh]">
            
            {/* Modal Header */}
            <div className="bg-slate-900 text-white p-4 flex items-center justify-between print:hidden">
              <div className="flex items-center gap-2">
                <FileCheck className="w-5 h-5 text-teal-400" />
                <span className="font-bold text-sm">Official OPD Prescription Record</span>
              </div>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handlePrint}
                  className="px-3 py-1.5 rounded-xl bg-teal-600 hover:bg-teal-700 text-white text-xs font-bold flex items-center gap-1.5 cursor-pointer transition-colors"
                >
                  <Printer className="w-3.5 h-3.5" />
                  <span>Print Slip</span>
                </button>
                <button
                  type="button"
                  onClick={() => setViewingRx(null)}
                  className="p-1.5 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 cursor-pointer"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>
            </div>

            {/* Printable Prescription Document Body */}
            <div className="p-8 overflow-y-auto space-y-6 text-slate-900 font-sans">
              
              {/* Hospital Banner */}
              <div className="border-b-2 border-slate-900 pb-4 flex items-start justify-between">
                <div>
                  <div className="flex items-center gap-2">
                    <Building2 className="w-6 h-6 text-purple-700" />
                    <h2 className="text-xl font-black tracking-tight text-slate-900">{hospitalName}</h2>
                  </div>
                  <p className="text-xs text-slate-500 mt-0.5">Department of {viewingRx.department} • OPD Clinical Service</p>
                  <p className="text-[10px] text-slate-400 font-mono">ABDM Integrated Healthcare Provider Node</p>
                </div>

                <div className="text-right">
                  <div className="text-xs font-mono font-bold text-purple-900 bg-purple-50 px-2 py-0.5 rounded border border-purple-200 inline-block">
                    {viewingRx.id}
                  </div>
                  <div className="text-[11px] text-slate-500 mt-1">Date: <strong>{viewingRx.date}</strong></div>
                </div>
              </div>

              {/* Patient Demographics Box */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 p-3.5 bg-slate-50 rounded-2xl border border-slate-200 text-xs">
                <div>
                  <span className="text-[10px] text-slate-400 font-bold uppercase block">Patient Name</span>
                  <span className="font-bold text-slate-900">{viewingRx.patientName}</span>
                </div>
                <div>
                  <span className="text-[10px] text-slate-400 font-bold uppercase block">UHID</span>
                  <span className="font-mono font-bold text-purple-700">{viewingRx.uhid}</span>
                </div>
                <div>
                  <span className="text-[10px] text-slate-400 font-bold uppercase block">Age / Gender</span>
                  <span className="font-bold text-slate-800">{viewingRx.age} yrs / {viewingRx.gender}</span>
                </div>
                <div>
                  <span className="text-[10px] text-slate-400 font-bold uppercase block">Department</span>
                  <span className="font-semibold text-slate-800">{viewingRx.department}</span>
                </div>
              </div>

              {/* Clinical Impression & Diagnosis */}
              <div className="space-y-1">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">Diagnosis / Impression</span>
                <p className="text-xs font-bold text-slate-800 bg-slate-100/70 p-2.5 rounded-xl border border-slate-200">
                  {viewingRx.diagnosis || 'Clinical evaluation completed.'}
                </p>
              </div>

              {/* Rx Medicines Table */}
              <div className="space-y-2">
                <div className="flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-purple-900">
                  <Pill className="w-4 h-4 text-purple-700" />
                  <span>Rx Prescribed Medications</span>
                </div>

                <div className="border border-slate-200 rounded-2xl overflow-hidden">
                  <table className="w-full text-left text-xs">
                    <thead className="bg-slate-100 text-slate-700 font-mono text-[10px] uppercase">
                      <tr>
                        <th className="py-2.5 px-3">#</th>
                        <th className="py-2.5 px-3">Medicine Name</th>
                        <th className="py-2.5 px-3">Dosage</th>
                        <th className="py-2.5 px-3">Frequency</th>
                        <th className="py-2.5 px-3">Duration</th>
                        <th className="py-2.5 px-3">Instructions</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {viewingRx.medications.map((med, idx) => (
                        <tr key={idx} className="hover:bg-slate-50/50">
                          <td className="py-2.5 px-3 font-mono text-slate-400">{idx + 1}</td>
                          <td className="py-2.5 px-3 font-bold text-slate-900">{med.name}</td>
                          <td className="py-2.5 px-3 font-mono text-slate-700">{med.dosage}</td>
                          <td className="py-2.5 px-3 text-slate-700">{med.frequency}</td>
                          <td className="py-2.5 px-3 text-slate-700">{med.duration}</td>
                          <td className="py-2.5 px-3 text-slate-500 italic">{med.instructions || 'As advised'}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* Advice / Notes */}
              {viewingRx.clinicalNotes && (
                <div className="space-y-1">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">Doctor Advice &amp; Instructions</span>
                  <p className="text-xs text-slate-700 leading-relaxed p-3 bg-amber-50/50 rounded-xl border border-amber-200">
                    {viewingRx.clinicalNotes}
                  </p>
                </div>
              )}

              {/* Doctor Sign-off */}
              <div className="pt-6 border-t border-slate-200 flex items-end justify-between">
                <div className="text-[10px] text-slate-400 space-y-0.5">
                  <div>Electronically generated through hospital HIS console.</div>
                  <div>Valid across all AIIMS / ABDM registered pharmacies.</div>
                </div>

                <div className="text-right space-y-1">
                  <div className="font-mono text-xs text-purple-700 font-bold border-b border-slate-300 pb-1 inline-block">
                    {viewingRx.doctorName}
                  </div>
                  <div className="text-[10px] text-slate-500">Authorized Medical Practitioner</div>
                  <div className="text-[9px] text-slate-400 font-mono">MCI Reg Validated • Security Hash #8920</div>
                </div>
              </div>

            </div>

            {/* Modal Bottom Bar */}
            <div className="p-4 bg-slate-50 border-t border-slate-200 flex justify-between items-center print:hidden">
              <span className="text-xs text-slate-500 font-mono">
                Status: <strong className="text-emerald-700 capitalize">{viewingRx.status.replace('_', ' ')}</strong>
              </span>
              <button
                type="button"
                onClick={() => setViewingRx(null)}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-900 text-white rounded-xl text-xs font-bold cursor-pointer"
              >
                Close Window
              </button>
            </div>

          </div>
        </div>
      )}

    </div>
  );
};
